# This is a basic workflow that is manually triggered

name: sample workflow 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
       
    - name: make
      run: gcc test.c -o test

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    
    - name: test
      run: ./test | grep "Hello, World"