# This is a basic workflow that is manually triggered

name: sample workflow 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
       
    - name: make
      run: gcc test.c -o /tmp/sid.out

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: ls
      run: ls -al /tmp
    - name: test
      run: /tmp/sid.out | grep "Hello, World"